---
title: Your awesome title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: GitHub User
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
twitter_username: your-twitter-handle
github_username: your-github-handle
show_excerpts: true
